### ISSUE TITLE
感觉含中文字符的文件应该以utf-8保存

### ISSUE THREAD

**Issue by jiamo** [codefollower/OpenJDK-Research#2]
有些文件用notpad++打开是 utf-8 无BOM 格式编码。 vs2013 编译起来有问题。 但转成utf-8格式编码之后就没有问题了。

**Comment by codefollower** [comment]
这里的HotSpot代码版本太低了，直接去http://hg.openjdk.java.net/jdk8u/jdk8u-dev 下吧
我平时用vs 2012，用jdk8u-dev的代码调试，加注释的代码是另一份并用EditPlus编辑(用utf-8存储是没有bom的)，之所以没在vs 2012上面修改，是因为每加一次注释都要编译一次，不想这样做。

**Comment by jiamo** [comment]
哦。 用最新的代码，需要加入两个依赖库， psapi.lib 和 version.lib. 还有个问题。编译成功之后 只会生成jvm.dll 并不能直接运行。[在Windows平台构建与调试HotSpot](https://github.com/codefollower/OpenJDK-Research/blob/master/hotspot/my-docs/%E5%9C%A8Windows%E5%B9%B3%E5%8F%B0%E6%9E%84%E5%BB%BA%E4%B8%8E%E8%B0%83%E8%AF%95HotSpot.md)这里是不是差个步骤？ 如果只是替换系统dll 怎么能断下来呢？

**Comment by codefollower** [comment]
这有两篇最新的文档，也是我写的
http://hllvm.group.iteye.com/group/topic/41271
http://hllvm.group.iteye.com/group/topic/41290
